#!/usr/bin/env python3
"""Generate the arm64 hand-written dyngen ops headers.

Emits real arm64 bodies for the whitelisted native ops (control primitives,
the scalar-integer compute core, memory, branches, and floating point);
every other op keeps a loud abort stub, unreachable while the translate
whitelist excludes it.
"""
import os
import re

# Resolve the x86_64 declaration surface relative to this script so the
# generator runs from any checkout location.
_HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(
    os.path.join(_HERE, "..", "..", "..", "..", "..", "Unix", "dyngen_precompiled"))
GEN_RE = re.compile(r"^DEFINE_GEN\((gen_op_[A-Za-z0-9_]+),void,\(([^)]*)\)\)")

HEADER = """/*
 *  %s - hand-written arm64 backend ops
 *
 *  PocketShaver arm64 JIT backend (C) 2026 Sierra Burkhart
 *  Kheperix (C) 2003-2005 Gwenole Beauchesne
 *
 *  Generated by cpu/jit/arm64/gen-arm64-ops.py from the x86_64 declaration
 *  surface. Real bodies exist for the whitelisted native ops; every other
 *  op traps at translate time via kpx_jit_unimplemented_op.
 */

#ifdef DYNGEN_IMPL
#include "cpu/jit/arm64/arm64-emit.hpp"
#endif

#ifndef DEFINE_CST
#define DEFINE_CST(NAME, VALUE)
#endif
"""
FOOTER = "\n#undef DEFINE_CST\n#undef DEFINE_GEN\n"
CST = "DEFINE_CST(op_exec_return_offset,0x34L)\n"

TREG = {"T0": "A64_T0", "T1": "A64_T1", "T2": "A64_T2"}

# ------------------------------------------------------------------ control primitives

def invoke(pre, post=""):
    return pre + "\ta64_emit_call(*this, (uintptr)param1);\n" + post

REAL = {}
REAL["gen_op_jmp_fast"] = ("\tconst intptr rel = (intptr)param1 - (intptr)code_ptr();\n"
                           "\temit_32(a64_b(rel));\n")
REAL["gen_op_jmp_slow"] = "\ta64_emit_jmp_abs(*this, (uintptr)param1);\n"
REAL["gen_op_jmp_A0"] = "\temit_32(a64_br(A64_T0));\n"
REAL["gen_op_mov_ad_A0_im"] = "\ta64_emit_mov_imm64(*this, A64_T0, (uint64)param1);\n"
REAL["gen_op_invoke"] = invoke("")
REAL["gen_op_invoke_T0"] = invoke("\temit_32(a64_mov_w(0, A64_T0));\n")
REAL["gen_op_invoke_T0_T1"] = invoke("\temit_32(a64_mov_w(0, A64_T0));\n\temit_32(a64_mov_w(1, A64_T1));\n")
REAL["gen_op_invoke_T0_T1_T2"] = invoke("\temit_32(a64_mov_w(0, A64_T0));\n\temit_32(a64_mov_w(1, A64_T1));\n\temit_32(a64_mov_w(2, A64_T2));\n")
REAL["gen_op_invoke_T0_ret_T0"] = invoke("\temit_32(a64_mov_w(0, A64_T0));\n", "\temit_32(a64_mov_w(A64_T0, 0));\n")
REAL["gen_op_invoke_im"] = invoke("\ta64_emit_mov_imm32(*this, 0, (uint32)param2);\n")
REAL["gen_op_invoke_CPU"] = invoke("\temit_32(a64_mov_x(0, A64_CPU));\n")
REAL["gen_op_invoke_CPU_T0"] = invoke("\temit_32(a64_mov_x(0, A64_CPU));\n\temit_32(a64_mov_w(1, A64_T0));\n")
REAL["gen_op_invoke_CPU_im"] = invoke("\temit_32(a64_mov_x(0, A64_CPU));\n\ta64_emit_mov_imm32(*this, 1, (uint32)param2);\n")
REAL["gen_op_invoke_CPU_im_im"] = invoke("\temit_32(a64_mov_x(0, A64_CPU));\n\ta64_emit_mov_imm32(*this, 1, (uint32)param2);\n\ta64_emit_mov_imm32(*this, 2, (uint32)param3);\n")
REAL["gen_op_invoke_CPU_A0_ret_A0"] = invoke("\temit_32(a64_mov_x(0, A64_CPU));\n\temit_32(a64_mov_x(1, A64_T0));\n", "\temit_32(a64_mov_x(A64_T0, 0));\n")
for name in [n for n in list(REAL) if n.startswith("gen_op_invoke")]:
    REAL[name.replace("gen_op_invoke", "gen_op_invoke_direct", 1)] = REAL[name]

# Prologue also pins VMBASE (x23) = VMBaseDiff for inline fastmem (the value
# is baked at emission time: op_execute is generated at CPU construction,
# after vm_init) and saves d8-d11 — the FP value plan hands those to
# generated code as scratch, but their low halves are AAPCS64 callee-saved
# toward op_execute's own caller (host frames keeping live doubles in d8-d11
# across execute() would be silently corrupted otherwise).
# 13 prologue instructions -> op_exec_return_offset = 0x34.
REAL["gen_op_execute"] = (
    "\tconst uintptr vmbase = kpx_vm_base();\n"
    "#ifdef MEM_BULK\n"
    "\tif (!vmbase) kpx_jit_unimplemented_op(\"op_execute: vm_init() must precede JIT construction\");\n"
    "#endif\n"
    "\temit_32(a64_stp_x_pre(A64_FP, A64_LR, A64_SP, -0x60));\n"
    "\temit_32(a64_mov_from_sp(A64_FP));\n"
    "\temit_32(a64_stp_x(A64_CPU, A64_T0, A64_SP, 0x10));\n"
    "\temit_32(a64_stp_x(A64_T1, A64_T2, A64_SP, 0x20));\n"
    "\temit_32(a64_str_x(A64_VMBASE, A64_SP, 0x30));\n"
    "\temit_32(a64_stp_d(8, 9, A64_SP, 0x40));\n"
    "\temit_32(a64_stp_d(10, 11, A64_SP, 0x50));\n"
    "\temit_32(a64_mov_x(A64_CPU, 1));\n"
    "\ta64_emit_mov_imm64(*this, A64_VMBASE, (uint64)vmbase);\n"
    "\temit_32(a64_br(0));\n"
    "\temit_32(a64_ldp_d(10, 11, A64_SP, 0x50));\n"
    "\temit_32(a64_ldp_d(8, 9, A64_SP, 0x40));\n"
    "\temit_32(a64_ldr_x(A64_VMBASE, A64_SP, 0x30));\n"
    "\temit_32(a64_ldp_x(A64_T1, A64_T2, A64_SP, 0x20));\n"
    "\temit_32(a64_ldp_x(A64_CPU, A64_T0, A64_SP, 0x10));\n"
    "\temit_32(a64_ldp_x_post(A64_FP, A64_LR, A64_SP, 0x60));\n"
    "\temit_32(a64_ret());\n")

REAL["gen_op_set_PC_im"] = ("\ta64_emit_mov_imm32(*this, A64_X16, (uint32)param1);\n"
                            "\temit_32(a64_str_w(A64_X16, A64_CPU, (uint32)kpx_jit_pc_offset(cpu())));\n")
REAL["gen_op_spcflags_check"] = ("\temit_32(a64_ldr_w(A64_X16, A64_CPU, (uint32)kpx_jit_spcflags_offset(cpu())));\n"
                                 "\tjmp_addr[0] = code_ptr();\n"
                                 "\temit_32(a64_cbz_w(A64_X16, 0));\n")
REAL["gen_op_jump_next_A0"] = ("\temit_32(a64_mov_x(0, A64_CPU));\n\temit_32(a64_mov_x(1, A64_T0));\n"
                               "\ta64_emit_call(*this, (uintptr)&kpx_jit_jump_next);\n"
                               "\temit_32(a64_cbz_x(0, 8));\n\temit_32(a64_br(0));\n")

# ------------------------------------------------------------------ scalar-integer compute core
# Each function below returns a C++ body string. Offsets come from cpu() at gen time.

def emit(*lines):
    return "".join("\t" + l + "\n" for l in lines)

def gpr_off(n):  return "(uint32)kpx_jit_gpr_offset(cpu(), %d)" % n
def E(insn):     return "emit_32(%s);" % insn

# T-register moves to/from CPU state
def moves(name):
    m = re.match(r"gen_op_(load|store)_(T[012])_GPR(\d+)$", name)
    if m:
        d, r, n = m.group(1), TREG[m.group(2)], int(m.group(3))
        insn = "a64_ldr_w(%s, A64_CPU, %s)" if d == "load" else "a64_str_w(%s, A64_CPU, %s)"
        return emit(E(insn % (r, gpr_off(n))))
    special = {
        "gen_op_load_T0_CR":  ("a64_ldr_w(A64_T0, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))", 1),
        "gen_op_store_T0_CR": ("a64_str_w(A64_T0, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))", 1),
        "gen_op_load_T0_CTR": ("a64_ldr_w(A64_T0, A64_CPU, (uint32)kpx_jit_ctr_offset(cpu()))", 1),
        "gen_op_store_T0_CTR":("a64_str_w(A64_T0, A64_CPU, (uint32)kpx_jit_ctr_offset(cpu()))", 1),
        # VRSAVE is a plain uint32 SPR (mfspr/mtspr 256), not vector state; it
        # reaches the JIT via the whitelisted MFSPR/MTSPR case, so it needs a
        # real body even though the AltiVec compute ops stay generic.
        "gen_op_load_T0_VRSAVE": ("a64_ldr_w(A64_T0, A64_CPU, (uint32)kpx_jit_vrsave_offset(cpu()))", 1),
        "gen_op_store_T0_VRSAVE":("a64_str_w(A64_T0, A64_CPU, (uint32)kpx_jit_vrsave_offset(cpu()))", 1),
        "gen_op_load_T0_LR":  ("a64_ldr_w(A64_T0, A64_CPU, (uint32)kpx_jit_lr_offset(cpu()))", 1),
        "gen_op_store_T0_LR": ("a64_str_w(A64_T0, A64_CPU, (uint32)kpx_jit_lr_offset(cpu()))", 1),
        "gen_op_load_T0_PC":  ("a64_ldr_w(A64_T0, A64_CPU, (uint32)kpx_jit_pc_offset(cpu()))", 1),
        "gen_op_store_T0_PC": ("a64_str_w(A64_T0, A64_CPU, (uint32)kpx_jit_pc_offset(cpu()))", 1),
        "gen_op_set_PC_T0":   ("a64_str_w(A64_T0, A64_CPU, (uint32)kpx_jit_pc_offset(cpu()))", 1),
    }
    if name in special:
        return emit(E(special[name][0]))
    if name == "gen_op_load_T0_CTR_aligned":
        return emit(E("a64_ldr_w(A64_T0, A64_CPU, (uint32)kpx_jit_ctr_offset(cpu()))"),
                    E("a64_movz_w(A64_X16, 3, 0)"), E("a64_bic_reg(A64_T0, A64_T0, A64_X16)"))
    if name == "gen_op_load_T0_LR_aligned":
        return emit(E("a64_ldr_w(A64_T0, A64_CPU, (uint32)kpx_jit_lr_offset(cpu()))"),
                    E("a64_movz_w(A64_X16, 3, 0)"), E("a64_bic_reg(A64_T0, A64_T0, A64_X16)"))
    if name == "gen_op_store_im_LR":
        return emit("a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);",
                    E("a64_str_w(A64_X16, A64_CPU, (uint32)kpx_jit_lr_offset(cpu()))"))
    if name == "gen_op_load_T0_XER":
        return emit(E("a64_mov_x(0, A64_CPU)"), "a64_emit_call(*this, (uintptr)&kpx_op_load_xer);",
                    E("a64_mov_w(A64_T0, 0)"))
    if name == "gen_op_store_T0_XER":
        return emit(E("a64_mov_x(0, A64_CPU)"), E("a64_mov_w(1, A64_T0)"),
                    "a64_emit_call(*this, (uintptr)&kpx_op_store_xer);")
    return None

def alu(name):
    # mov
    m = re.match(r"gen_op_mov_32_(T[012])_(T[012])$", name)
    if m: return emit(E("a64_mov_w(%s, %s)" % (TREG[m.group(1)], TREG[m.group(2)])))
    m = re.match(r"gen_op_mov_32_(T[012])_0$", name)
    if m: return emit(E("a64_mov_w(%s, A64_ZR)" % TREG[m.group(1)]))
    m = re.match(r"gen_op_mov_32_(T[012])_im$", name)
    if m: return emit("a64_emit_mov_imm32(*this, %s, (uint32)param1);" % TREG[m.group(1)])
    # add/sub reg, const, im
    m = re.match(r"gen_op_(add|sub)_32_(T[01])_(T[012])$", name)
    if m:
        op = "a64_add_reg" if m.group(1) == "add" else "a64_sub_reg"
        d = TREG[m.group(2)]; s = TREG[m.group(3)]
        return emit(E("%s(%s, %s, %s)" % (op, d, d, s)))
    m = re.match(r"gen_op_(add|sub)_32_(T[01])_(\d+)$", name)
    if m:
        op = "a64_add_imm" if m.group(1) == "add" else "a64_sub_imm"
        d = TREG[m.group(2)]
        return emit(E("%s(%s, %s, %s)" % (op, d, d, m.group(3))))
    m = re.match(r"gen_op_(add|sub)_32_(T[01])_im$", name)
    if m:
        op = "a64_add_reg" if m.group(1) == "add" else "a64_sub_reg"
        d = TREG[m.group(2)]
        return emit("a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);", E("%s(%s, %s, A64_X16)" % (op, d, d)))
    # logical reg
    logic = {"and": "a64_and_reg", "or": "a64_orr_reg", "xor": "a64_eor_reg",
             "orc": "a64_orn_reg", "andc": "a64_bic_reg"}
    m = re.match(r"gen_op_(and|or|xor|orc|andc)_32_T0_T1$", name)
    if m: return emit(E("%s(A64_T0, A64_T0, A64_T1)" % logic[m.group(1)]))
    m = re.match(r"gen_op_(and|or|xor)_32_T0_im$", name)
    if m:
        return emit("a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);", E("%s(A64_T0, A64_T0, A64_X16)" % logic[m.group(1)]))
    # nand/nor/eqv = op then MVN
    nlogic = {"nand": "a64_and_reg", "nor": "a64_orr_reg", "eqv": "a64_eor_reg"}
    m = re.match(r"gen_op_(nand|nor|eqv)_32_T0_T1$", name)
    if m: return emit(E("%s(A64_T0, A64_T0, A64_T1)" % nlogic[m.group(1)]), E("a64_mvn_reg(A64_T0, A64_T0)"))
    if name == "gen_op_neg_32_T0": return emit(E("a64_neg_reg(A64_T0, A64_T0)"))
    m = re.match(r"gen_op_not_32_(T[01])$", name)   # LOGICAL not (0->1, nonzero->0)
    if m:
        d = TREG[m.group(1)]
        return emit(E("a64_cmp_imm(%s, 0)" % d), E("a64_cset(%s, A64_EQ)" % d))
    # multiply
    if name in ("gen_op_umul_32_T0_T1", "gen_op_smul_32_T0_T1"):
        return emit(E("a64_mul(A64_T0, A64_T0, A64_T1)"))
    if name == "gen_op_mulhw_T0_T1":
        return emit(E("a64_smull(A64_X16, A64_T0, A64_T1)"), E("a64_lsr_imm_x(A64_X16, A64_X16, 32)"), E("a64_mov_w(A64_T0, A64_X16)"))
    if name == "gen_op_mulhwu_T0_T1":
        return emit(E("a64_umull(A64_X16, A64_T0, A64_T1)"), E("a64_lsr_imm_x(A64_X16, A64_X16, 32)"), E("a64_mov_w(A64_T0, A64_X16)"))
    if name == "gen_op_mulli_T0_im":
        return emit("a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);", E("a64_mul(A64_T0, A64_T0, A64_X16)"))
    return None

def shifts(name):
    # immediate shifts: PARAM1 = shift amount
    if name == "gen_op_lsl_32_T0_im": return emit("if ((uint32)param1) emit_32(a64_lsl_imm(A64_T0, A64_T0, (int)param1));")
    if name == "gen_op_lsr_32_T0_im": return emit("if ((uint32)param1) emit_32(a64_lsr_imm(A64_T0, A64_T0, (int)param1));")
    if name == "gen_op_asr_32_T0_im": return emit("if ((uint32)param1) emit_32(a64_asr_imm(A64_T0, A64_T0, (int)param1));")
    if name == "gen_op_rol_32_T0_im": return emit("if ((uint32)param1) emit_32(a64_ror_imm(A64_T0, A64_T0, 32 - (int)param1));")
    if name == "gen_op_ror_32_T0_im": return emit("if ((uint32)param1) emit_32(a64_ror_imm(A64_T0, A64_T0, (int)param1));")
    # variable shifts (32-bit, count mod 32)
    if name == "gen_op_lsl_32_T0_T1": return emit(E("a64_lslv(A64_T0, A64_T0, A64_T1)"))
    if name == "gen_op_lsr_32_T0_T1": return emit(E("a64_lsrv(A64_T0, A64_T0, A64_T1)"))
    if name == "gen_op_asr_32_T0_T1": return emit(E("a64_asrv(A64_T0, A64_T0, A64_T1)"))
    if name == "gen_op_rol_32_T0_T1":  # rotl(T0, T1) = ror(T0, -T1)
        return emit(E("a64_neg_reg(A64_X16, A64_T1)"), E("a64_rorv(A64_T0, A64_T0, A64_X16)"))
    if name == "gen_op_ror_32_T0_T1":
        return emit(E("a64_rorv(A64_T0, A64_T0, A64_T1)"))
    # PPC 6-bit slw/srw: 64-bit shift of zero-extended T0 by (T1 & 0x3f)
    if name == "gen_op_slw_T0_T1":
        return emit(E("a64_movz_w(A64_X17, 0x3f, 0)"), E("a64_and_reg(A64_X16, A64_T1, A64_X17)"),
                    E("a64_lslv_x(A64_X16, A64_T0, A64_X16)"), E("a64_mov_w(A64_T0, A64_X16)"))
    if name == "gen_op_srw_T0_T1":
        return emit(E("a64_movz_w(A64_X17, 0x3f, 0)"), E("a64_and_reg(A64_X16, A64_T1, A64_X17)"),
                    E("a64_lsrv_x(A64_X16, A64_T0, A64_X16)"), E("a64_mov_w(A64_T0, A64_X16)"))
    # sraw / srawi set XER.CA -> helper
    if name == "gen_op_sraw_T0_T1":
        return emit(E("a64_mov_x(0, A64_CPU)"), E("a64_mov_w(1, A64_T0)"), E("a64_mov_w(2, A64_T1)"),
                    "a64_emit_call(*this, (uintptr)&kpx_op_sraw);", E("a64_mov_w(A64_T0, 0)"))
    if name == "gen_op_sraw_T0_im":
        return emit(E("a64_mov_x(0, A64_CPU)"), E("a64_mov_w(1, A64_T0)"),
                    "a64_emit_mov_imm32(*this, 2, (uint32)param1);",
                    "a64_emit_call(*this, (uintptr)&kpx_op_srawi);", E("a64_mov_w(A64_T0, 0)"))
    # extends / clz / bswap
    if name == "gen_op_se_8_32_T0":  return emit(E("a64_sxtb(A64_T0, A64_T0)"))
    if name == "gen_op_se_16_32_T0": return emit(E("a64_sxth(A64_T0, A64_T0)"))
    if name == "gen_op_se_16_32_T1": return emit(E("a64_sxth(A64_T1, A64_T1)"))
    if name == "gen_op_ze_8_32_T0":  return emit(E("a64_uxtb(A64_T0, A64_T0)"))
    if name == "gen_op_ze_16_32_T0": return emit(E("a64_uxth(A64_T0, A64_T0)"))
    if name == "gen_op_cntlzw_32_T0": return emit(E("a64_clz(A64_T0, A64_T0)"))
    if name == "gen_op_bswap_16_T0": return emit(E("a64_uxth(A64_T0, A64_T0)"), E("a64_rev16(A64_T0, A64_T0)"))
    if name == "gen_op_bswap_32_T0": return emit(E("a64_rev(A64_T0, A64_T0)"))
    # rlw family: PARAM1 = SH (or mask for rlwnm); PARAM2 = mask
    if name == "gen_op_rlwinm_T0_T1":
        return emit("if ((uint32)param1) emit_32(a64_ror_imm(A64_T0, A64_T0, 32 - (int)param1));",
                    "a64_emit_mov_imm32(*this, A64_X16, (uint32)param2);", E("a64_and_reg(A64_T0, A64_T0, A64_X16)"))
    if name == "gen_op_rlwnm_T0_T1":  # rotl(T0, T1) & PARAM1
        return emit(E("a64_neg_reg(A64_X16, A64_T1)"), E("a64_rorv(A64_T0, A64_T0, A64_X16)"),
                    "a64_emit_mov_imm32(*this, A64_X17, (uint32)param1);", E("a64_and_reg(A64_T0, A64_T0, A64_X17)"))
    if name == "gen_op_rlwimi_T0_T1":  # (rotl(T1,SH) & mask) | (T0 & ~mask)
        return emit("if ((uint32)param1) emit_32(a64_ror_imm(A64_X16, A64_T1, 32 - (int)param1)); else emit_32(a64_mov_w(A64_X16, A64_T1));",
                    "a64_emit_mov_imm32(*this, A64_X17, (uint32)param2);",
                    E("a64_and_reg(A64_X16, A64_X16, A64_X17)"), E("a64_bic_reg(A64_T0, A64_T0, A64_X17)"),
                    E("a64_orr_reg(A64_T0, A64_T0, A64_X16)"))
    return None

# add/sub with XER, divides, mullwo, nego -> helper calls
XER_HELPERS_2 = ["addo","addc","addco","adde","addeo","subfo","subfc","subfco","subfe","subfeo",
                 "mullwo","divw","divwo","divwu","divwuo"]
XER_HELPERS_1 = ["addme","addmeo","addze","addzeo","subfme","subfmeo","subfze","subfzeo","nego"]

def xer_ops(name):
    m = re.match(r"gen_op_(\w+)_T0_T1$", name)
    if m and m.group(1) in XER_HELPERS_2:
        h = m.group(1)
        return emit(E("a64_mov_x(0, A64_CPU)"), E("a64_mov_w(1, A64_T0)"), E("a64_mov_w(2, A64_T1)"),
                    "a64_emit_call(*this, (uintptr)&kpx_op_%s);" % h, E("a64_mov_w(A64_T0, 0)"))
    m = re.match(r"gen_op_(\w+)_T0$", name)
    if m and m.group(1) in XER_HELPERS_1:
        h = m.group(1)
        return emit(E("a64_mov_x(0, A64_CPU)"), E("a64_mov_w(1, A64_T0)"),
                    "a64_emit_call(*this, (uintptr)&kpx_op_%s);" % h, E("a64_mov_w(A64_T0, 0)"))
    if name in ("gen_op_addc_T0_im", "gen_op_subfc_T0_im"):
        h = "addc_im" if "addc" in name else "subfc_im"
        return emit(E("a64_mov_x(0, A64_CPU)"), E("a64_mov_w(1, A64_T0)"),
                    "a64_emit_mov_imm32(*this, 2, (uint32)param1);",
                    "a64_emit_call(*this, (uintptr)&kpx_op_%s);" % h, E("a64_mov_w(A64_T0, 0)"))
    return None

def _nibble(gt_cond, lt_cond):
    # build CR nibble (LT=8,GT=4,EQ=2) | XER.so into A64_X16 after a CMP
    return (emit(E("a64_movz_w(A64_X16, 2, 0)"), E("a64_movz_w(A64_X17, 4, 0)"),
                 "emit_32(a64_csel(A64_X16, A64_X17, A64_X16, %s));" % gt_cond,
                 E("a64_movz_w(A64_X17, 8, 0)"),
                 "emit_32(a64_csel(A64_X16, A64_X17, A64_X16, %s));" % lt_cond,
                 E("a64_ldrb(A64_X17, A64_CPU, (uint32)kpx_jit_xer_offset(cpu()))"),
                 E("a64_orr_reg(A64_T0, A64_X16, A64_X17)")))

def compares(name):
    if name == "gen_op_compare_T0_T1":  return emit(E("a64_cmp_reg(A64_T0, A64_T1)")) + _nibble("A64_GT", "A64_LT")
    if name == "gen_op_compare_logical_T0_T1": return emit(E("a64_cmp_reg(A64_T0, A64_T1)")) + _nibble("A64_HI", "A64_LO")
    if name == "gen_op_compare_T0_im":
        return emit("a64_emit_mov_imm32(*this, A64_X9, (uint32)param1);", E("a64_cmp_reg(A64_T0, A64_X9)")) + _nibble("A64_GT", "A64_LT")
    if name == "gen_op_compare_logical_T0_im":
        return emit("a64_emit_mov_imm32(*this, A64_X9, (uint32)param1);", E("a64_cmp_reg(A64_T0, A64_X9)")) + _nibble("A64_HI", "A64_LO")
    if name == "gen_op_compare_T0_0":  return emit(E("a64_cmp_imm(A64_T0, 0)")) + _nibble("A64_GT", "A64_LT")
    if name == "gen_op_compare_logical_T0_0": return emit(E("a64_cmp_imm(A64_T0, 0)")) + _nibble("A64_HI", "A64_LO")
    return None

def cr_ops(name):
    if name == "gen_op_record_cr1":
        # cr = (cr & ~0x0f000000) | ((fpscr >> 4) & 0x0f000000)
        return emit(E("a64_ldr_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"),
                    E("a64_movz_w(A64_X9, 0x0f00, 1)"),
                    E("a64_bic_reg(A64_X16, A64_X16, A64_X9)"),
                    E("a64_ldr_w(A64_X10, A64_CPU, (uint32)kpx_jit_fpscr_offset(cpu()))"),
                    E("a64_lsr_imm(A64_X10, A64_X10, 4)"),
                    E("a64_and_reg(A64_X10, A64_X10, A64_X9)"),
                    E("a64_orr_reg(A64_X16, A64_X16, A64_X10)"),
                    E("a64_str_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"))
    if name == "gen_op_record_cr0_T0":
        return emit(E("a64_ldr_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"),
                    E("a64_lsl_imm(A64_X16, A64_X16, 4)"), E("a64_lsr_imm(A64_X16, A64_X16, 4)"),
                    E("a64_ldrb(A64_X9, A64_CPU, (uint32)kpx_jit_xer_offset(cpu()))"),
                    E("a64_lsl_imm(A64_X9, A64_X9, 28)"),
                    E("a64_cmp_imm(A64_T0, 0)"),
                    E("a64_movz_w(A64_X10, 0x2000, 1)"),
                    E("a64_movz_w(A64_X11, 0x4000, 1)"), E("a64_csel(A64_X10, A64_X11, A64_X10, A64_GT)"),
                    E("a64_movz_w(A64_X11, 0x8000, 1)"), E("a64_csel(A64_X10, A64_X11, A64_X10, A64_LT)"),
                    E("a64_orr_reg(A64_X16, A64_X16, A64_X10)"), E("a64_orr_reg(A64_X16, A64_X16, A64_X9)"),
                    E("a64_str_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"))
    m = re.match(r"gen_op_load_(T[01])_cr(\d)$", name)
    if m:
        r = TREG[m.group(1)]; sh = 28 - 4 * int(m.group(2))
        return emit(E("a64_ldr_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"),
                    ("emit_32(a64_lsr_imm(%s, A64_X16, %d));" % (r, sh)) if sh else E("a64_mov_w(%s, A64_X16)" % r),
                    E("a64_movz_w(A64_X17, 0xf, 0)"), E("a64_and_reg(%s, %s, A64_X17)" % (r, r)))
    m = re.match(r"gen_op_store_(T[01])_cr(\d)$", name)
    if m:
        r = TREG[m.group(1)]; sh = 28 - 4 * int(m.group(2))
        return emit(E("a64_ldr_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"),
                    E("a64_movz_w(A64_X9, 0xf, 0)"),
                    ("emit_32(a64_lsl_imm(A64_X9, A64_X9, %d));" % sh) if sh else "",
                    E("a64_bic_reg(A64_X16, A64_X16, A64_X9)"),
                    E("a64_movz_w(A64_X10, 0xf, 0)"), E("a64_and_reg(A64_X10, %s, A64_X10)" % r),
                    ("emit_32(a64_lsl_imm(A64_X10, A64_X10, %d));" % sh) if sh else "",
                    E("a64_orr_reg(A64_X16, A64_X16, A64_X10)"),
                    E("a64_str_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"))
    m = re.match(r"gen_op_load_(T[01])_crb(\d+)$", name)
    if m:
        r = TREG[m.group(1)]; sh = 31 - int(m.group(2))
        return emit(E("a64_ldr_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"),
                    ("emit_32(a64_lsr_imm(%s, A64_X16, %d));" % (r, sh)) if sh else E("a64_mov_w(%s, A64_X16)" % r),
                    E("a64_movz_w(A64_X17, 1, 0)"), E("a64_and_reg(%s, %s, A64_X17)" % (r, r)))
    m = re.match(r"gen_op_store_(T[01])_crb(\d+)$", name)
    if m:
        r = TREG[m.group(1)]; sh = 31 - int(m.group(2))
        return emit(E("a64_ldr_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"),
                    E("a64_movz_w(A64_X9, 1, 0)"),
                    ("emit_32(a64_lsl_imm(A64_X9, A64_X9, %d));" % sh) if sh else "",
                    E("a64_bic_reg(A64_X16, A64_X16, A64_X9)"),
                    E("a64_movz_w(A64_X10, 1, 0)"), E("a64_and_reg(A64_X10, %s, A64_X10)" % r),
                    ("emit_32(a64_lsl_imm(A64_X10, A64_X10, %d));" % sh) if sh else "",
                    E("a64_orr_reg(A64_X16, A64_X16, A64_X10)"),
                    E("a64_str_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"))
    if name == "gen_op_mtcrf_T0_im":
        return emit(E("a64_ldr_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"),
                    "a64_emit_mov_imm32(*this, A64_X9, (uint32)param1);",
                    E("a64_bic_reg(A64_X16, A64_X16, A64_X9)"),
                    E("a64_and_reg(A64_X10, A64_T0, A64_X9)"),
                    E("a64_orr_reg(A64_X16, A64_X16, A64_X10)"),
                    E("a64_str_w(A64_X16, A64_CPU, (uint32)kpx_jit_cr_offset(cpu()))"))
    return None

def ppc_plain(name):
    # PPC ALU ops without flag side effects
    if name == "gen_op_subf_T0_T1":   # T0 = T1 - T0
        return emit(E("a64_sub_reg(A64_T0, A64_T1, A64_T0)"))
    return None

# ------------------------------------------------------------------ memory ops
# EA = T1 + OFFSET computed with W-form arithmetic (guest addresses wrap mod
# 2^32). Under MEM_BULK the access itself is emitted inline (fastmem): flat
# [VMBASE, EA(uxtw)] plus REV byteswap behind the same coarse pre-filter
# vm.hpp uses (EA >> 19 >= 0xbff covers both kernel-data windows and
# everything past the mapped guest space); the filter's cold path calls the
# old kpx_vm_* helpers, which apply the exact translation rules. Without
# MEM_BULK every access takes the helper call as before.

def _ea_w0(kind):
    # Effective address into w0 (the helper's first argument)
    if kind == "0":
        return [E("a64_mov_w(0, A64_T1)")]
    if kind == "T2":
        return [E("a64_add_reg(0, A64_T1, A64_T2)")]
    # im: D-form displacement, sign-extended; prefer single-insn imm12 forms
    return ["if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));",
            "else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));",
            "else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));",
            "else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }"]

def _helper_body(pre, helper, tail=()):
    return "".join("\t" + l + "\n" for l in
                   list(pre) + ["a64_emit_call(*this, (uintptr)&%s);" % helper] + list(tail))

def _fastmem_body(pre, hot, helper, tail_cold=(), tail_shared=()):
    # pre (EA in w0, value in w1/x1 for stores) ; coarse filter ; hot access
    # ; skip over the 5-insn cold helper call ; shared tail. Branch offsets
    # are exact instruction counts of this fixed shape.
    h, tc = len(hot), len(tail_cold)
    lines = list(pre)
    lines += [E("a64_lsr_imm(A64_X16, 0, 19)"),
              E("a64_cmp_imm(A64_X16, 0xbff)"),
              E("a64_b_cond(A64_HS, %d)" % ((h + 2) * 4))]
    lines += hot
    lines += [E("a64_b(%d)" % ((5 + tc + 1) * 4))]
    lines += ["a64_emit_call(*this, (uintptr)&%s);" % helper]
    lines += list(tail_cold)
    lines += list(tail_shared)
    return ("#ifdef KPX_JIT_INSTRUMENT\n"
            "\t{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }\n"
            "#endif\n" + "".join("\t" + l + "\n" for l in lines))

def _mem_bulk_gated(fast, legacy):
    return "#ifdef MEM_BULK\n" + fast + "#else\n" + legacy + "#endif\n"

MEM_READ = {"u8": (1, "kpx_vm_read_1", None), "s8": (1, "kpx_vm_read_1", "a64_sxtb"),
            "u16": (2, "kpx_vm_read_2", None), "s16": (2, "kpx_vm_read_2", "a64_sxth"),
            "u32": (4, "kpx_vm_read_4", None), "s32": (4, "kpx_vm_read_4", None)}
MEM_WRITE = {"8": (1, "kpx_vm_write_1"), "16": (2, "kpx_vm_write_2"), "32": (4, "kpx_vm_write_4")}

READ_HOT = {1: [E("a64_ldrb_uxtw(0, A64_VMBASE, 0)")],
            2: [E("a64_ldrh_uxtw(0, A64_VMBASE, 0)"), E("a64_rev16(0, 0)")],
            4: [E("a64_ldr_w_uxtw(0, A64_VMBASE, 0)"), E("a64_rev(0, 0)")]}
WRITE_HOT = {1: [E("a64_strb_uxtw(1, A64_VMBASE, 0)")],
             2: [E("a64_rev16(A64_X16, 1)"), E("a64_strh_uxtw(A64_X16, A64_VMBASE, 0)")],
             4: [E("a64_rev(A64_X16, 1)"), E("a64_str_w_uxtw(A64_X16, A64_VMBASE, 0)")]}

def mem(name):
    m = re.match(r"gen_op_load_(u8|s8|u16|s16|u32|s32)_T0_T1_(0|im|T2)$", name)
    if m:
        sz, helper, ext = MEM_READ[m.group(1)]
        tail = [E("%s(A64_T0, 0)" % ext)] if ext else [E("a64_mov_w(A64_T0, 0)")]
        ea = _ea_w0(m.group(2))
        return _mem_bulk_gated(_fastmem_body(ea, READ_HOT[sz], helper, (), tail),
                               _helper_body(ea, helper, tail))
    m = re.match(r"gen_op_store_(8|16|32)_T0_T1_(0|im|T2)$", name)
    if m:
        sz, helper = MEM_WRITE[m.group(1)]
        pre = _ea_w0(m.group(2)) + [E("a64_mov_w(1, A64_T0)")]
        return _mem_bulk_gated(_fastmem_body(pre, WRITE_HOT[sz], helper),
                               _helper_body(pre, helper))
    m = re.match(r"gen_op_(lmw|stmw)_T0_(\d+|im)$", name)
    if m:
        h = "kpx_op_" + m.group(1)
        r = ("a64_emit_mov_imm32(*this, 2, (uint32)param1);" if m.group(2) == "im"
             else E("a64_movz_w(2, %s, 0)" % m.group(2)))
        return emit(E("a64_mov_x(0, A64_CPU)"), E("a64_mov_w(1, A64_T0)"), r,
                    "a64_emit_call(*this, (uintptr)&%s);" % h)
    if name == "gen_op_lwarx_T0_T1":
        return emit(E("a64_mov_x(0, A64_CPU)"), E("a64_mov_w(1, A64_T1)"),
                    "a64_emit_call(*this, (uintptr)&kpx_op_lwarx);", E("a64_mov_w(A64_T0, 0)"))
    if name == "gen_op_stwcx_T0_T1":
        return emit(E("a64_mov_x(0, A64_CPU)"), E("a64_mov_w(1, A64_T0)"), E("a64_mov_w(2, A64_T1)"),
                    "a64_emit_call(*this, (uintptr)&kpx_op_stwcx);")
    if name == "gen_op_dcbz_T0":
        return emit(E("a64_mov_w(0, A64_T0)"), "a64_emit_call(*this, (uintptr)&kpx_op_dcbz);")
    return None

# ------------------------------------------------------------------ branch ops
# prep_branch_bo_*: inputs T1 = CR bit (0/1, conditional variants only);
# outputs T1 = taken flag (exactly 0/1), T2 = decremented CTR (decrement
# variants, stored to CPU state). Must not touch T0 (BCLR/BCCTR target).

_DEC = [E("a64_ldr_w(A64_T2, A64_CPU, (uint32)kpx_jit_ctr_offset(cpu()))"),
        E("a64_sub_imm(A64_T2, A64_T2, 1)"),
        E("a64_str_w(A64_T2, A64_CPU, (uint32)kpx_jit_ctr_offset(cpu()))")]

def _prep(dec, ctr_cond, cond_cond):
    # T1 = [ctr test] && [cond test]; each cond is an A64 cc applied to a
    # compare-with-zero of T2 (ctr) / T1 (cr bit)
    lines = list(_DEC) if dec else []
    if ctr_cond and cond_cond:
        lines += [E("a64_cmp_imm(A64_T2, 0)"), E("a64_cset(A64_X16, %s)" % ctr_cond),
                  E("a64_cmp_imm(A64_T1, 0)"), E("a64_cset(A64_X17, %s)" % cond_cond),
                  E("a64_and_reg(A64_T1, A64_X16, A64_X17)")]
    elif ctr_cond:
        lines += [E("a64_cmp_imm(A64_T2, 0)"), E("a64_cset(A64_T1, %s)" % ctr_cond)]
    elif cond_cond:
        lines += [E("a64_cmp_imm(A64_T1, 0)"), E("a64_cset(A64_T1, %s)" % cond_cond)]
    else:
        lines += [E("a64_movz_w(A64_T1, 1, 0)")]
    return "".join("\t" + l + "\n" for l in lines)

PREP_BRANCH = {
    # suffix: (decrement, ctr condition, cond condition) — cond tests the CR
    # bit in T1 (NE = branch-if-true, EQ = branch-if-false); ctr tests the
    # decremented CTR in T2 (NE = branch-if-ctr-nonzero, EQ = if-ctr-zero)
    "0000": (True,  "A64_NE", "A64_EQ"),
    "0001": (True,  "A64_EQ", "A64_EQ"),
    "001x": (False, None,     "A64_EQ"),
    "0100": (True,  "A64_NE", "A64_NE"),
    "0101": (True,  "A64_EQ", "A64_NE"),
    "011x": (False, None,     "A64_NE"),
    "1x00": (True,  "A64_NE", None),
    "1x01": (True,  "A64_EQ", None),
    "1x1x": (False, None,     None),
}

def branches(name):
    m = re.match(r"gen_op_prep_branch_bo_(\w+)$", name)
    if m and m.group(1) in PREP_BRANCH:
        dec, ctr_c, cond_c = PREP_BRANCH[m.group(1)]
        return _prep(dec, ctr_c, cond_c)
    if name == "gen_op_branch_1_T0":
        return emit(E("a64_str_w(A64_T0, A64_CPU, (uint32)kpx_jit_pc_offset(cpu()))"))
    if name == "gen_op_branch_1_im":
        return emit("a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);",
                    E("a64_str_w(A64_X16, A64_CPU, (uint32)kpx_jit_pc_offset(cpu()))"))
    if name == "gen_op_branch_2_T0_im":    # pc = T1 ? T0 : PARAM1
        return emit("a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);",
                    E("a64_cmp_imm(A64_T1, 0)"),
                    E("a64_csel(A64_X16, A64_T0, A64_X16, A64_NE)"),
                    E("a64_str_w(A64_X16, A64_CPU, (uint32)kpx_jit_pc_offset(cpu()))"))
    if name == "gen_op_branch_2_im_im":    # pc = T1 ? PARAM1 : PARAM2
        return emit("a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);",
                    "a64_emit_mov_imm32(*this, A64_X17, (uint32)param2);",
                    E("a64_cmp_imm(A64_T1, 0)"),
                    E("a64_csel(A64_X16, A64_X16, A64_X17, A64_NE)"),
                    E("a64_str_w(A64_X16, A64_CPU, (uint32)kpx_jit_pc_offset(cpu()))"))
    # Direct block chaining: deposit patchable B slots (retargeted to the
    # resolver trampolines at translate time, then to target entry points at
    # run time). Slots MUST be B imm26 — run-time retargets span the whole
    # translation cache, beyond CBZ's +/-1MB. The placeholder a64_b(0) is a
    # well-formed branch-to-self so the patcher can classify the site; the
    # translator always retargets it before the block is published.
    if name == "gen_op_branch_chain_1":
        return emit("jmp_addr[0] = code_ptr();",
                    E("a64_b(0)"))
    if name == "gen_op_branch_chain_2":
        return emit(E("a64_cbz_w(A64_T1, 8)"),   # T1==0 -> not-taken slot (fixed local skip, never patched)
                    "jmp_addr[0] = code_ptr();",
                    E("a64_b(0)"),               # taken -> li[0] (tpc)
                    "jmp_addr[1] = code_ptr();",
                    E("a64_b(0)"))               # not taken -> li[1] (npc)
    return None

# ------------------------------------------------------------------ floating point
# Value plan: d8 = F0, d9 = F1, d10 = F2, d11 = FD (callee-saved low halves).
# Arithmetic goes through kpx_fp_* helpers that replicate the interpreter's
# execute_fp_arith exactly (incl. the FPSCR[FPRF] classify); the FPSCR-less
# move ops (fmov/fabs/fneg/fnabs) emit inline.

FREG = {"F0": 8, "F1": 9, "F2": 10, "FD": 11}
FP_ARITH2 = ("fadd", "fadds", "fsub", "fsubs", "fmul", "fmuls", "fdiv", "fdivs")
FP_ARITH3 = ("fmadd", "fmadds", "fmsub", "fmsubs", "fnmadd", "fnmadds", "fnmsub", "fnmsubs")

def fp(name):
    m = re.match(r"gen_op_fmov_(FD|F[012])_(FD|F[012])$", name)
    if m: return emit(E("a64_fmov_d(%d, %d)" % (FREG[m.group(1)], FREG[m.group(2)])))
    if name == "gen_op_fabs_FD_F0": return emit(E("a64_fabs_d(11, 8)"))
    if name == "gen_op_fneg_FD_F0": return emit(E("a64_fneg_d(11, 8)"))
    if name == "gen_op_fnabs_FD_F0": return emit(E("a64_fabs_d(11, 8)"), E("a64_fneg_d(11, 11)"))
    m = re.match(r"gen_op_(\w+)_FD_F0_F1$", name)
    if m and m.group(1) in FP_ARITH2:
        return emit(E("a64_mov_x(0, A64_CPU)"), E("a64_fmov_d(0, 8)"), E("a64_fmov_d(1, 9)"),
                    "a64_emit_call(*this, (uintptr)&kpx_fp_%s);" % m.group(1), E("a64_fmov_d(11, 0)"))
    m = re.match(r"gen_op_(\w+)_FD_F0_F1_F2$", name)
    if m and m.group(1) in FP_ARITH3:
        return emit(E("a64_mov_x(0, A64_CPU)"), E("a64_fmov_d(0, 8)"), E("a64_fmov_d(1, 9)"),
                    E("a64_fmov_d(2, 10)"),
                    "a64_emit_call(*this, (uintptr)&kpx_fp_%s);" % m.group(1), E("a64_fmov_d(11, 0)"))
    m = re.match(r"gen_op_load_(F[012])_FPR(\d+)$", name)
    if m:
        return emit(E("a64_ldr_d(%d, A64_CPU, (uint32)kpx_jit_fpr_offset(cpu(), %s))"
                      % (FREG[m.group(1)], m.group(2))))
    m = re.match(r"gen_op_store_(FD|F[012])_FPR(\d+)$", name)
    if m:
        return emit(E("a64_str_d(%d, A64_CPU, (uint32)kpx_jit_fpr_offset(cpu(), %s))"
                      % (FREG[m.group(1)], m.group(2))))
    m = re.match(r"gen_op_load_(double|single)_FD_T1_(0|im|T2)$", name)
    if m:
        ea = _ea_w0(m.group(2))
        if m.group(1) == "double":
            fast = _fastmem_body(ea,
                                 [E("a64_ldr_x_uxtw(0, A64_VMBASE, 0)"), E("a64_rev_x(0, 0)")],
                                 "kpx_vm_read_8", (), [E("a64_fmov_d_x(11, 0)")])
            legacy = _helper_body(ea, "kpx_vm_read_8", [E("a64_fmov_d_x(11, 0)")])
        else:
            # (double)float is exactly FCVT, so lfs inlines fully; the cold
            # path keeps the C converter and lands its result via x0
            fast = _fastmem_body(ea,
                                 [E("a64_ldr_w_uxtw(0, A64_VMBASE, 0)"), E("a64_rev(0, 0)"),
                                  E("a64_fmov_s_w(0, 0)"), E("a64_fcvt_d_s(11, 0)")],
                                 "kpx_fp_load_single", [E("a64_fmov_d_x(11, 0)")], ())
            legacy = _helper_body(ea, "kpx_fp_load_single", [E("a64_fmov_d_x(11, 0)")])
        return _mem_bulk_gated(fast, legacy)
    m = re.match(r"gen_op_store_(double|single)_F0_T1_(0|im|T2)$", name)
    if m:
        pre = _ea_w0(m.group(2)) + [E("a64_fmov_x_d(1, 8)")]
        if m.group(1) == "double":
            fast = _fastmem_body(pre,
                                 [E("a64_rev_x(A64_X16, 1)"), E("a64_str_x_uxtw(A64_X16, A64_VMBASE, 0)")],
                                 "kpx_vm_write_8")
            return _mem_bulk_gated(fast, _helper_body(pre, "kpx_vm_write_8"))
        # stfs stays a helper on all configs: the out-of-range denormalization
        # cases (exponent outside 874..896) are NOT a plain FCVT
        return _helper_body(pre, "kpx_fp_store_single")
    return None

def body_for(name):
    if name in REAL:
        return REAL[name]
    for fn in (moves, alu, shifts, xer_ops, compares, cr_ops, ppc_plain, mem, branches, fp):
        b = fn(name)
        if b is not None:
            return b
    return None

# ------------------------------------------------------------------ emit headers

# arm64-only ops with no x86 counterpart (callers are __aarch64__-gated).
# gen_op_sheep_guard_im: trap-chaining resume guard emitted after a generic
# execute_sheep invoke whose handler deterministically resumes at the next
# instruction. Continue inline iff regs().pc == param1 (the expected resume
# pc) AND spcflags are clear; otherwise fall through into the exit stanza
# the translator emits right after this op. Deposits the patchable CBZ in
# jmp_addr[0]; the translator retargets it past the exit stanza (same
# protocol as gen_op_spcflags_check) and must re-NULL the slot.
EXTRA_PPC_OPS = [
    ("gen_op_sheep_guard_im", "long param1",
     "\ta64_emit_mov_imm32(*this, A64_X16, (uint32)param1);\n"
     "\temit_32(a64_ldr_w(A64_X17, A64_CPU, (uint32)kpx_jit_pc_offset(cpu())));\n"
     "\temit_32(a64_eor_reg(A64_X16, A64_X16, A64_X17));\n"
     "\temit_32(a64_ldr_w(A64_X17, A64_CPU, (uint32)kpx_jit_spcflags_offset(cpu())));\n"
     "\temit_32(a64_orr_reg(A64_X16, A64_X16, A64_X17));\n"
     "\tjmp_addr[0] = code_ptr();\n"
     "\temit_32(a64_cbz_w(A64_X16, 0));\n"),
]

def convert(src_path, dst_path, dst_name, is_basic):
    ops = []
    with open(src_path) as f:
        for line in f:
            m = GEN_RE.match(line)
            if m: ops.append((m.group(1), m.group(2)))
    out = [HEADER % dst_name]
    if is_basic: out.append(CST)
    real = 0
    for nm, args in ops:
        out.append("\nDEFINE_GEN(%s,void,(%s))\n#ifdef DYNGEN_IMPL\n{\n" % (nm, args))
        b = body_for(nm)
        if b is not None:
            out.append(b); real += 1
        else:
            out.append('\tkpx_jit_unimplemented_op("%s");\n' % nm)
        out.append("}\n#endif\n")
    if not is_basic:
        for nm, args, body in EXTRA_PPC_OPS:
            out.append("\nDEFINE_GEN(%s,void,(%s))\n#ifdef DYNGEN_IMPL\n{\n" % (nm, args))
            out.append(body)
            out.append("}\n#endif\n")
            real += 1
    out.append(FOOTER)
    open(dst_path, "w").write("".join(out))
    print("%s: %d ops (%d real, %d stub)" % (dst_name, len(ops), real, len(ops) - real))

convert(SRC + "/basic-dyngen-ops-x86_64_macos.hpp", SRC + "/basic-dyngen-ops-arm64.hpp", "basic-dyngen-ops-arm64.hpp", True)
convert(SRC + "/ppc-dyngen-ops-x86_64_macos.hpp", SRC + "/ppc-dyngen-ops-arm64.hpp", "ppc-dyngen-ops-arm64.hpp", False)
