/*
 *  basic-dyngen-ops-arm64.hpp - hand-written arm64 backend ops
 *
 *  PocketShaver arm64 JIT backend (C) 2026 Sierra Burkhart
 *  Kheperix (C) 2003-2005 Gwenole Beauchesne
 *
 *  Generated by cpu/jit/arm64/gen-arm64-ops.py from the x86_64 declaration
 *  surface. Real bodies exist for the whitelisted native ops; every other
 *  op traps at translate time via kpx_jit_unimplemented_op.
 */

#ifdef DYNGEN_IMPL
#include "cpu/jit/arm64/arm64-emit.hpp"
#endif

#ifndef DEFINE_CST
#define DEFINE_CST(NAME, VALUE)
#endif
DEFINE_CST(op_exec_return_offset,0x34L)

DEFINE_GEN(gen_op_invoke,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_T0,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(0, A64_T0));
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_T0_T1,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(0, A64_T0));
	emit_32(a64_mov_w(1, A64_T1));
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_T0_T1_T2,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(0, A64_T0));
	emit_32(a64_mov_w(1, A64_T1));
	emit_32(a64_mov_w(2, A64_T2));
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_T0_ret_T0,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(0, A64_T0));
	a64_emit_call(*this, (uintptr)param1);
	emit_32(a64_mov_w(A64_T0, 0));
}
#endif

DEFINE_GEN(gen_op_invoke_im,void,(long param1, long param2))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, 0, (uint32)param2);
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_CPU,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_x(0, A64_CPU));
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_CPU_T0,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_x(0, A64_CPU));
	emit_32(a64_mov_w(1, A64_T0));
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_CPU_im,void,(long param1, long param2))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_x(0, A64_CPU));
	a64_emit_mov_imm32(*this, 1, (uint32)param2);
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_CPU_im_im,void,(long param1, long param2, long param3))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_x(0, A64_CPU));
	a64_emit_mov_imm32(*this, 1, (uint32)param2);
	a64_emit_mov_imm32(*this, 2, (uint32)param3);
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_CPU_A0_ret_A0,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_x(0, A64_CPU));
	emit_32(a64_mov_x(1, A64_T0));
	a64_emit_call(*this, (uintptr)param1);
	emit_32(a64_mov_x(A64_T0, 0));
}
#endif

DEFINE_GEN(gen_op_invoke_direct,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_direct_T0,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(0, A64_T0));
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_direct_T0_T1,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(0, A64_T0));
	emit_32(a64_mov_w(1, A64_T1));
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_direct_T0_T1_T2,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(0, A64_T0));
	emit_32(a64_mov_w(1, A64_T1));
	emit_32(a64_mov_w(2, A64_T2));
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_direct_T0_ret_T0,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(0, A64_T0));
	a64_emit_call(*this, (uintptr)param1);
	emit_32(a64_mov_w(A64_T0, 0));
}
#endif

DEFINE_GEN(gen_op_invoke_direct_im,void,(long param1, long param2))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, 0, (uint32)param2);
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_direct_CPU,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_x(0, A64_CPU));
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_direct_CPU_T0,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_x(0, A64_CPU));
	emit_32(a64_mov_w(1, A64_T0));
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_direct_CPU_im,void,(long param1, long param2))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_x(0, A64_CPU));
	a64_emit_mov_imm32(*this, 1, (uint32)param2);
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_direct_CPU_im_im,void,(long param1, long param2, long param3))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_x(0, A64_CPU));
	a64_emit_mov_imm32(*this, 1, (uint32)param2);
	a64_emit_mov_imm32(*this, 2, (uint32)param3);
	a64_emit_call(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_invoke_direct_CPU_A0_ret_A0,void,(long param1))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_x(0, A64_CPU));
	emit_32(a64_mov_x(1, A64_T0));
	a64_emit_call(*this, (uintptr)param1);
	emit_32(a64_mov_x(A64_T0, 0));
}
#endif

DEFINE_GEN(gen_op_jmp_fast,void,(long param1))
#ifdef DYNGEN_IMPL
{
	const intptr rel = (intptr)param1 - (intptr)code_ptr();
	emit_32(a64_b(rel));
}
#endif

DEFINE_GEN(gen_op_jmp_slow,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_jmp_abs(*this, (uintptr)param1);
}
#endif

DEFINE_GEN(gen_op_neg_32_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_neg_reg(A64_T0, A64_T0));
}
#endif

DEFINE_GEN(gen_op_not_32_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_cmp_imm(A64_T0, 0));
	emit_32(a64_cset(A64_T0, A64_EQ));
}
#endif

DEFINE_GEN(gen_op_not_32_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_cmp_imm(A64_T1, 0));
	emit_32(a64_cset(A64_T1, A64_EQ));
}
#endif

DEFINE_GEN(gen_op_se_8_32_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sxtb(A64_T0, A64_T0));
}
#endif

DEFINE_GEN(gen_op_ze_8_32_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_uxtb(A64_T0, A64_T0));
}
#endif

DEFINE_GEN(gen_op_add_32_T0_1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_imm(A64_T0, A64_T0, 1));
}
#endif

DEFINE_GEN(gen_op_add_32_T0_2,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_imm(A64_T0, A64_T0, 2));
}
#endif

DEFINE_GEN(gen_op_add_32_T0_4,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_imm(A64_T0, A64_T0, 4));
}
#endif

DEFINE_GEN(gen_op_add_32_T0_8,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_imm(A64_T0, A64_T0, 8));
}
#endif

DEFINE_GEN(gen_op_add_32_T1_1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_imm(A64_T1, A64_T1, 1));
}
#endif

DEFINE_GEN(gen_op_add_32_T1_2,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_imm(A64_T1, A64_T1, 2));
}
#endif

DEFINE_GEN(gen_op_add_32_T1_4,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_imm(A64_T1, A64_T1, 4));
}
#endif

DEFINE_GEN(gen_op_add_32_T1_8,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_imm(A64_T1, A64_T1, 8));
}
#endif

DEFINE_GEN(gen_op_bswap_16_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_uxth(A64_T0, A64_T0));
	emit_32(a64_rev16(A64_T0, A64_T0));
}
#endif

DEFINE_GEN(gen_op_bswap_32_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_rev(A64_T0, A64_T0));
}
#endif

DEFINE_GEN(gen_op_mov_32_T0_0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(A64_T0, A64_ZR));
}
#endif

DEFINE_GEN(gen_op_mov_32_T1_0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(A64_T1, A64_ZR));
}
#endif

DEFINE_GEN(gen_op_mov_32_T2_0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(A64_T2, A64_ZR));
}
#endif

DEFINE_GEN(gen_op_or_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_orr_reg(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_or_32_T0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);
	emit_32(a64_orr_reg(A64_T0, A64_T0, A64_X16));
}
#endif

DEFINE_GEN(gen_op_se_16_32_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sxth(A64_T0, A64_T0));
}
#endif

DEFINE_GEN(gen_op_se_16_32_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sxth(A64_T1, A64_T1));
}
#endif

DEFINE_GEN(gen_op_sub_32_T0_1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_imm(A64_T0, A64_T0, 1));
}
#endif

DEFINE_GEN(gen_op_sub_32_T0_2,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_imm(A64_T0, A64_T0, 2));
}
#endif

DEFINE_GEN(gen_op_sub_32_T0_4,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_imm(A64_T0, A64_T0, 4));
}
#endif

DEFINE_GEN(gen_op_sub_32_T0_8,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_imm(A64_T0, A64_T0, 8));
}
#endif

DEFINE_GEN(gen_op_sub_32_T1_1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_imm(A64_T1, A64_T1, 1));
}
#endif

DEFINE_GEN(gen_op_sub_32_T1_2,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_imm(A64_T1, A64_T1, 2));
}
#endif

DEFINE_GEN(gen_op_sub_32_T1_4,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_imm(A64_T1, A64_T1, 4));
}
#endif

DEFINE_GEN(gen_op_sub_32_T1_8,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_imm(A64_T1, A64_T1, 8));
}
#endif

DEFINE_GEN(gen_op_ze_16_32_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_uxth(A64_T0, A64_T0));
}
#endif

DEFINE_GEN(gen_op_add_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_reg(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_add_32_T0_T2,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_reg(A64_T0, A64_T0, A64_T2));
}
#endif

DEFINE_GEN(gen_op_add_32_T0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);
	emit_32(a64_add_reg(A64_T0, A64_T0, A64_X16));
}
#endif

DEFINE_GEN(gen_op_add_32_T1_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_reg(A64_T1, A64_T1, A64_T0));
}
#endif

DEFINE_GEN(gen_op_add_32_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_add_reg(A64_T1, A64_T1, A64_T2));
}
#endif

DEFINE_GEN(gen_op_add_32_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);
	emit_32(a64_add_reg(A64_T1, A64_T1, A64_X16));
}
#endif

DEFINE_GEN(gen_op_and_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_and_reg(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_and_32_T0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);
	emit_32(a64_and_reg(A64_T0, A64_T0, A64_X16));
}
#endif

DEFINE_GEN(gen_op_asr_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_asrv(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_asr_32_T0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	if ((uint32)param1) emit_32(a64_asr_imm(A64_T0, A64_T0, (int)param1));
}
#endif

DEFINE_GEN(gen_op_eqv_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_eor_reg(A64_T0, A64_T0, A64_T1));
	emit_32(a64_mvn_reg(A64_T0, A64_T0));
}
#endif

DEFINE_GEN(gen_op_lsl_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_lslv(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_lsl_32_T0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	if ((uint32)param1) emit_32(a64_lsl_imm(A64_T0, A64_T0, (int)param1));
}
#endif

DEFINE_GEN(gen_op_lsr_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_lsrv(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_lsr_32_T0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	if ((uint32)param1) emit_32(a64_lsr_imm(A64_T0, A64_T0, (int)param1));
}
#endif

DEFINE_GEN(gen_op_mov_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_mov_32_T0_T2,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(A64_T0, A64_T2));
}
#endif

DEFINE_GEN(gen_op_mov_32_T0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, A64_T0, (uint32)param1);
}
#endif

DEFINE_GEN(gen_op_mov_32_T1_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(A64_T1, A64_T0));
}
#endif

DEFINE_GEN(gen_op_mov_32_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(A64_T1, A64_T2));
}
#endif

DEFINE_GEN(gen_op_mov_32_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, A64_T1, (uint32)param1);
}
#endif

DEFINE_GEN(gen_op_mov_32_T2_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(A64_T2, A64_T0));
}
#endif

DEFINE_GEN(gen_op_mov_32_T2_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mov_w(A64_T2, A64_T1));
}
#endif

DEFINE_GEN(gen_op_mov_32_T2_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, A64_T2, (uint32)param1);
}
#endif

DEFINE_GEN(gen_op_mov_ad_A0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm64(*this, A64_T0, (uint64)param1);
}
#endif

DEFINE_GEN(gen_op_mov_ad_A1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	kpx_jit_unimplemented_op("gen_op_mov_ad_A1_im");
}
#endif

DEFINE_GEN(gen_op_mov_ad_A2_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	kpx_jit_unimplemented_op("gen_op_mov_ad_A2_im");
}
#endif

DEFINE_GEN(gen_op_nor_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_orr_reg(A64_T0, A64_T0, A64_T1));
	emit_32(a64_mvn_reg(A64_T0, A64_T0));
}
#endif

DEFINE_GEN(gen_op_orc_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_orn_reg(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_rol_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_neg_reg(A64_X16, A64_T1));
	emit_32(a64_rorv(A64_T0, A64_T0, A64_X16));
}
#endif

DEFINE_GEN(gen_op_rol_32_T0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	if ((uint32)param1) emit_32(a64_ror_imm(A64_T0, A64_T0, 32 - (int)param1));
}
#endif

DEFINE_GEN(gen_op_ror_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_rorv(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_ror_32_T0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	if ((uint32)param1) emit_32(a64_ror_imm(A64_T0, A64_T0, (int)param1));
}
#endif

DEFINE_GEN(gen_op_sub_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_reg(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_sub_32_T0_T2,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_reg(A64_T0, A64_T0, A64_T2));
}
#endif

DEFINE_GEN(gen_op_sub_32_T0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);
	emit_32(a64_sub_reg(A64_T0, A64_T0, A64_X16));
}
#endif

DEFINE_GEN(gen_op_sub_32_T1_T0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_reg(A64_T1, A64_T1, A64_T0));
}
#endif

DEFINE_GEN(gen_op_sub_32_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_sub_reg(A64_T1, A64_T1, A64_T2));
}
#endif

DEFINE_GEN(gen_op_sub_32_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);
	emit_32(a64_sub_reg(A64_T1, A64_T1, A64_X16));
}
#endif

DEFINE_GEN(gen_op_xor_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_eor_reg(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_xor_32_T0_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
	a64_emit_mov_imm32(*this, A64_X16, (uint32)param1);
	emit_32(a64_eor_reg(A64_T0, A64_T0, A64_X16));
}
#endif

DEFINE_GEN(gen_op_andc_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_bic_reg(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_nand_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_and_reg(A64_T0, A64_T0, A64_T1));
	emit_32(a64_mvn_reg(A64_T0, A64_T0));
}
#endif

DEFINE_GEN(gen_op_sdiv_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	kpx_jit_unimplemented_op("gen_op_sdiv_32_T0_T1");
}
#endif

DEFINE_GEN(gen_op_smul_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mul(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_udiv_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	kpx_jit_unimplemented_op("gen_op_udiv_32_T0_T1");
}
#endif

DEFINE_GEN(gen_op_umul_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_mul(A64_T0, A64_T0, A64_T1));
}
#endif

DEFINE_GEN(gen_op_xchg_32_T0_T1,void,(void))
#ifdef DYNGEN_IMPL
{
	kpx_jit_unimplemented_op("gen_op_xchg_32_T0_T1");
}
#endif

DEFINE_GEN(gen_op_load_s8_T0_T1_0,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 12));
	emit_32(a64_ldrb_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_sxtb(A64_T0, 0));
#else
	emit_32(a64_mov_w(0, A64_T1));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_sxtb(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_u8_T0_T1_0,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 12));
	emit_32(a64_ldrb_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	emit_32(a64_mov_w(0, A64_T1));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_store_8_T0_T1_0,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_mov_w(1, A64_T0));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 12));
	emit_32(a64_strb_uxtw(1, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_1);
#else
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_mov_w(1, A64_T0));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_1);
#endif
}
#endif

DEFINE_GEN(gen_op_load_s16_T0_T1_0,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldrh_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev16(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_sxth(A64_T0, 0));
#else
	emit_32(a64_mov_w(0, A64_T1));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_sxth(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_s32_T0_T1_0,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldr_w_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	emit_32(a64_mov_w(0, A64_T1));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_s8_T0_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 12));
	emit_32(a64_ldrb_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_sxtb(A64_T0, 0));
#else
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_sxtb(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_s8_T0_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 12));
	emit_32(a64_ldrb_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_sxtb(A64_T0, 0));
#else
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_sxtb(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_u16_T0_T1_0,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldrh_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev16(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	emit_32(a64_mov_w(0, A64_T1));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_u32_T0_T1_0,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldr_w_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	emit_32(a64_mov_w(0, A64_T1));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_u8_T0_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 12));
	emit_32(a64_ldrb_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_u8_T0_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 12));
	emit_32(a64_ldrb_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	a64_emit_call(*this, (uintptr)&kpx_vm_read_1);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_store_16_T0_T1_0,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_mov_w(1, A64_T0));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_rev16(A64_X16, 1));
	emit_32(a64_strh_uxtw(A64_X16, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_2);
#else
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_mov_w(1, A64_T0));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_2);
#endif
}
#endif

DEFINE_GEN(gen_op_store_32_T0_T1_0,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_mov_w(1, A64_T0));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_rev(A64_X16, 1));
	emit_32(a64_str_w_uxtw(A64_X16, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_4);
#else
	emit_32(a64_mov_w(0, A64_T1));
	emit_32(a64_mov_w(1, A64_T0));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_4);
#endif
}
#endif

DEFINE_GEN(gen_op_store_8_T0_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_mov_w(1, A64_T0));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 12));
	emit_32(a64_strb_uxtw(1, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_1);
#else
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_mov_w(1, A64_T0));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_1);
#endif
}
#endif

DEFINE_GEN(gen_op_store_8_T0_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_mov_w(1, A64_T0));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 12));
	emit_32(a64_strb_uxtw(1, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_1);
#else
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_mov_w(1, A64_T0));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_1);
#endif
}
#endif

DEFINE_GEN(gen_op_load_s16_T0_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldrh_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev16(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_sxth(A64_T0, 0));
#else
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_sxth(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_s16_T0_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldrh_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev16(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_sxth(A64_T0, 0));
#else
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_sxth(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_s32_T0_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldr_w_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_s32_T0_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldr_w_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_u16_T0_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldrh_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev16(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_u16_T0_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldrh_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev16(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	a64_emit_call(*this, (uintptr)&kpx_vm_read_2);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_u32_T0_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldr_w_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_load_u32_T0_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_ldr_w_uxtw(0, A64_VMBASE, 0));
	emit_32(a64_rev(0, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#else
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	a64_emit_call(*this, (uintptr)&kpx_vm_read_4);
	emit_32(a64_mov_w(A64_T0, 0));
#endif
}
#endif

DEFINE_GEN(gen_op_store_16_T0_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_mov_w(1, A64_T0));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_rev16(A64_X16, 1));
	emit_32(a64_strh_uxtw(A64_X16, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_2);
#else
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_mov_w(1, A64_T0));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_2);
#endif
}
#endif

DEFINE_GEN(gen_op_store_16_T0_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_mov_w(1, A64_T0));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_rev16(A64_X16, 1));
	emit_32(a64_strh_uxtw(A64_X16, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_2);
#else
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_mov_w(1, A64_T0));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_2);
#endif
}
#endif

DEFINE_GEN(gen_op_store_32_T0_T1_T2,void,(void))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_mov_w(1, A64_T0));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_rev(A64_X16, 1));
	emit_32(a64_str_w_uxtw(A64_X16, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_4);
#else
	emit_32(a64_add_reg(0, A64_T1, A64_T2));
	emit_32(a64_mov_w(1, A64_T0));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_4);
#endif
}
#endif

DEFINE_GEN(gen_op_store_32_T0_T1_im,void,(long param1))
#ifdef DYNGEN_IMPL
{
#ifdef MEM_BULK
#ifdef KPX_JIT_INSTRUMENT
	{ extern unsigned long kpx_jit_inline_mem_emitted; kpx_jit_inline_mem_emitted++; }
#endif
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_mov_w(1, A64_T0));
	emit_32(a64_lsr_imm(A64_X16, 0, 19));
	emit_32(a64_cmp_imm(A64_X16, 0xbff));
	emit_32(a64_b_cond(A64_HS, 16));
	emit_32(a64_rev(A64_X16, 1));
	emit_32(a64_str_w_uxtw(A64_X16, A64_VMBASE, 0));
	emit_32(a64_b(24));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_4);
#else
	if ((uint32)param1 == 0) emit_32(a64_mov_w(0, A64_T1));
	else if ((uint32)param1 < 4096) emit_32(a64_add_imm(0, A64_T1, (uint32)param1));
	else if ((uint32)-(uint32)param1 < 4096) emit_32(a64_sub_imm(0, A64_T1, (uint32)-(uint32)param1));
	else { a64_emit_mov_imm32(*this, A64_X16, (uint32)param1); emit_32(a64_add_reg(0, A64_T1, A64_X16)); }
	emit_32(a64_mov_w(1, A64_T0));
	a64_emit_call(*this, (uintptr)&kpx_vm_write_4);
#endif
}
#endif

DEFINE_GEN(gen_op_jmp_A0,void,(void))
#ifdef DYNGEN_IMPL
{
	emit_32(a64_br(A64_T0));
}
#endif

DEFINE_GEN(gen_op_execute,void,(void))
#ifdef DYNGEN_IMPL
{
	const uintptr vmbase = kpx_vm_base();
#ifdef MEM_BULK
	if (!vmbase) kpx_jit_unimplemented_op("op_execute: vm_init() must precede JIT construction");
#endif
	emit_32(a64_stp_x_pre(A64_FP, A64_LR, A64_SP, -0x60));
	emit_32(a64_mov_from_sp(A64_FP));
	emit_32(a64_stp_x(A64_CPU, A64_T0, A64_SP, 0x10));
	emit_32(a64_stp_x(A64_T1, A64_T2, A64_SP, 0x20));
	emit_32(a64_stp_x(A64_VMBASE, A64_VD, A64_SP, 0x30));
	emit_32(a64_stp_d(8, 9, A64_SP, 0x40));
	emit_32(a64_stp_d(10, 11, A64_SP, 0x50));
	emit_32(a64_mov_x(A64_CPU, 1));
	a64_emit_mov_imm64(*this, A64_VMBASE, (uint64)vmbase);
	emit_32(a64_br(0));
	emit_32(a64_ldp_d(10, 11, A64_SP, 0x50));
	emit_32(a64_ldp_d(8, 9, A64_SP, 0x40));
	emit_32(a64_ldp_x(A64_VMBASE, A64_VD, A64_SP, 0x30));
	emit_32(a64_ldp_x(A64_T1, A64_T2, A64_SP, 0x20));
	emit_32(a64_ldp_x(A64_CPU, A64_T0, A64_SP, 0x10));
	emit_32(a64_ldp_x_post(A64_FP, A64_LR, A64_SP, 0x60));
	emit_32(a64_ret());
}
#endif

#undef DEFINE_CST
#undef DEFINE_GEN
